drop table song;
drop table killing_part;
drop table member;
drop table artist;
drop table killing_part_like;
drop table killing_part_comment;

create table if not exists song
(
    id              bigint auto_increment,
    title           varchar(100) not null,
    artist_id       bigint       not null,
    length          integer      not null,
    video_id        varchar(20)  not null,
    album_cover_url text         not null,
    genre           varchar(255) check (genre in
                                        ('BALLAD', 'DANCE', 'HIPHOP', 'RHYTHM_AND_BLUES', 'INDIE',
                                         'ROCK_METAL', 'TROT', 'FOLK_BLUES', 'POP', 'JAZZ',
                                         'CLASSIC', 'J_POP', 'EDM', 'ETC')),
    created_at      timestamp(6) not null,
    primary key (id)
);

create table if not exists killing_part
(
    id           bigint auto_increment,
    start_second integer      not null,
    length       varchar(255) not null check (length in ('SHORT', 'STANDARD', 'LONG')),
    song_id      bigint       not null,
    like_count   integer      not null default 0,
    created_at   timestamp(6) not null,
    primary key (id)
);

create table if not exists member
(
    id         bigint auto_increment,
    email      varchar(100) not null,
    nickname   varchar(100) not null,
    created_at timestamp(6) not null,
    primary key (id)
);

create table if not exists killing_part_like
(
    id              bigint auto_increment,
    killing_part_id bigint       not null,
    member_id       bigint       not null,
    is_deleted      boolean      not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    primary key (id)
);

create table if not exists killing_part_comment
(
    id              bigint auto_increment,
    killing_part_id bigint       not null,
    content         varchar(200) not null,
    member_id       bigint       not null,
    created_at      timestamp(6) not null,
    primary key (id)
);

create table if not exists artist
(
    id                bigint generated by default as identity,
    name              varchar(50)  not null,
    profile_image_url text         not null,
    created_at        timestamp(6) not null,
    primary key (id)
);

INSERT INTO artist (name, profile_image_url, created_at) values ('NewJeans', 'http://i.maniadb.com/images/album/999/999126_1_f.jpg', now());
INSERT INTO artist (name, profile_image_url, created_at) values ('가수', 'http://i.maniadb.com/images/album/999/999126_1_f.jpg', now());
INSERT INTO artist (name, profile_image_url, created_at) values ('정국', 'http://i.maniadb.com/images/album/999/999126_1_f.jpg', now());

INSERT INTO song (title, artist_id, length, video_id, album_cover_url, created_at, genre)
VALUES ('Super Shy', 1, 200, 'ArmDp-zijuc',
        'http://i.maniadb.com/images/album/999/999126_1_f.jpg', now(), 'DANCE');
INSERT INTO song (title, artist_id, length, video_id, album_cover_url, created_at, genre)
VALUES ('노래', 2, 263, 'sjeifksl',
        'http://i.maniadb.com/images/album/29382/028492.jpg', now(), 'HIPHOP');
INSERT INTO song (title, artist_id, length, video_id, album_cover_url, created_at, genre)
VALUES ('Not Shy', 1, 200, 'ArmDp-zijuc',
        'http://i.maniadb.com/images/album/999/999126_1_f.jpg', now(), 'DANCE');
INSERT INTO song (title, artist_id, length, video_id, album_cover_url, created_at, genre)
VALUES ('Seven (feat. Latto) - Clean Ver.', 3, 186, 'UUSbUBYqU_8',
        'http://i.maniadb.com/images/album/1000/000246_1_f.jpg', now(), 'DANCE');

INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (10, 'SHORT', 1, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (15, 'LONG', 1, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (20, 'STANDARD', 1, 0, now());

INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (10, 'SHORT', 2, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (15, 'LONG', 2, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (20, 'STANDARD', 2, 0, now());

INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (10, 'SHORT', 3, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (15, 'LONG', 3, 0, now());
INSERT INTO killing_part (start_second, length, song_id, like_count, created_at)
VALUES (20, 'STANDARD', 3, 0, now());

INSERT INTO member (email, nickname, created_at)
VALUES ('email@naver.com', 'nickname', now());
