spring:
  profiles:
    active: local
  config:
    import: classpath:shook-security/application.yml

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shook;MODE=MySQL

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  config: classpath:logback/logback-local.xml

# Properties Only For Local
oauth2:
  google:
    access-token-url: http://localhost:8080/token
    member-info-url: http://localhost:8080/userinfo
    client-id: client
    client-secret: secret
    redirect-uri: redirect
  kakao:
    access-token-url: https://localhost:8080/oauth/token
    member-info-url: https://localhost:8080/v2/user/me
    client-id: client
    redirect-url: redirect

# Properties Only For Local
jwt:
  secret-code: asdkfwofk23ksdfowsrk4sdkf
  access-token-valid-time: 12000
  refresh-token-valid-time: 634000

# Properties Only For Local
cookie:
  valid-time: 634000

excel:
  video-url-delimiter: "v="
  killingpart-data-delimiter: " "
  song-length-suffix: "초"

# Properties Only For local
schedules:
  in-memory-token:
    cron: "0 0 0/1 * * *"
  in-memory-song:
    cron: "0 0 0/1 * * *" #1시간

# Actuator
management:
  endpoints:
    web:
      base-path: /status
    exposure:
      include: health
