spring:
  config:
    import: classpath:shook-security/application.yml

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shook

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: validate
