name: Backend Develop Deploy (CD)

on:
  workflow_dispatch:

jobs:
  build:
    name: Backend Deploy
    runs-on: shook-runner

    steps:
      - name: Log pwd
        shell: bash
        run: pwd
      - name: Deploy
        shell: bash
        run: bash /home/ubuntu/deploy.sh
