name: Backend Develop Deploy (CD)

on:
  workflow_dispatch:

jobs:
  build:
    name: Backend Develop Deploy
    runs-on: shook-runner

    steps:
      - name: Remove Legacy Repository
        shell: bash
        run: |
          pwd
          cd ..
          ls -al
          rm -rf 2023-shook
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_PAT }}
          submodules: recursive
      - name: Grant execute permission to gradlew
        shell: bash
        run: chmod +x backend/gradlew
      - name: Check Java Version
        shell: bash
        run: java --version
      - name: Gradlew bootJar
        shell: bash
        run: |
          cd backend
          ./gradlew bootJar
      - name: Copy Jar
        shell: bash
        run: cp backend/build/libs/shook-0.0.1-SNAPSHOT.jar /home/ubuntu/application-jar
      - name: Backend Deploy
        shell: bash
        run: bash /home/ubuntu/backend-deploy.sh
