name: Backend Develop Deploy (CD)

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Backend Deploy
    runs-on: shook-runner

    steps:
      - name: Deploy
        shell: bash
        run: bash /home/ubuntu/deploy.sh
