name: Frontend Production Deploy (CD)

on:
  workflow_dispatch:

jobs:
  build:
    name: Frontend Deploy
    runs-on: shook-prod
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setting env
        shell: bash
        run: |
          rm -rf frontend/.env
          mkdir frontend/.env
          echo "BASE_URL=${{secret.FRONT_PROD_BASE_URL}}" > frontend/.env/.env.production
      - name: Package clean install
        shell: bash
        run: |
          cd frontend
          npm ci
      - name: Build files
        shell: bash
        run: |
          cd frontend
          npm run build
      - name: Remove legacy static pages
        shell: bash
        run: rm -rf home/ubuntu/dist
      - name: Move generated new static pages
        shell: bash
        run: cp -r frontend/dist ~/
